env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp" # Where to clone the aosp-builder repo

# store our secrets here
    my_og_token: "ENCRYPTED[0276990e26d93085fb08a543241e40cf2b8034b53b6b8b3061c72dbfeb337ebc9457b3343a5c69be82f0f9cb3f48c0b5]" # main id
    REAL_REPO_OWNER: "ENCRYPTED[0276990e26d93085fb08a543241e40cf2b8034b53b6b8b3061c72dbfeb337ebc9457b3343a5c69be82f0f9cb3f48c0b5]" # main id

task:
    name: kernel
    timeout_in: 120m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
      greedy: true
    run_script:
      - git clone --depth=1 https://$REAL_REPO_OWNER:$my_og_token@github.com/reaPeR1010/4.19 /tmp/kernel -b main
      - cd /tmp/kernel
      - bash build_kramal.sh
