env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp" # Where to clone the aosp-builder repo

# store our secrets here
    GH_TOKEN: "ENCRYPTED[0276990e26d93085fb08a543241e40cf2b8034b53b6b8b3061c72dbfeb337ebc9457b3343a5c69be82f0f9cb3f48c0b5]" # main id

task:
    name: kernel
    timeout_in: 120m
    container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 32G
      greedy: true
    run_script:
      - git clone --depth=1 --single-branch https://${GH_TOKEN}@github.com/reaPeR1010/kernel_4.14 -b newtest x
      - cd x
      - curl -Ls https://gist.githubusercontent.com/reaPeR1010/3f8fb2febf704ee505a80bdda801285d/raw/41cf9469fe4227c74de021efe0b9d0dcc149045c/lav.sh | bash
