env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    my_og_token: "ENCRYPTED[0276990e26d93085fb08a543241e40cf2b8034b53b6b8b3061c72dbfeb337ebc9457b3343a5c69be82f0f9cb3f48c0b5]" # main id
    github_token: "ENCRYPTED[ec44f57dcf7b2c8d1a0e6b9d51c81e0c5a0f5105b6df12ace105c056586af8c729acb17c8acac5ef2db6c1c0f839f9a3]" # alt id
    bot_api: "ENCRYPTED[e09e9a0cc5e18746d2e09f1e0e3d23c5093407c11489831f87d4fea889b3e5e6b44d95bd27bc85a3caecd26c50080a54]"
    chat_id: "-1001510035003"
    git_cookies: 0
    du_key: 0 # disable dev_upload
    K19: 1 # kernel 4.19 or 4.4
    cc_lvl: "-3" # ccache com lvl
    part_id: "002" # to ensure all parts are in sync
    REAL_REPO_OWNER: "ENCRYPTED[0276990e26d93085fb08a543241e40cf2b8034b53b6b8b3061c72dbfeb337ebc9457b3343a5c69be82f0f9cb3f48c0b5]" # main id

# store information about git here
    gmail: ehteshammalik18998@gmail.com

task:
    name: R
    timeout_in: 120m
    container:
      dockerfile: nexgang
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
    down_background_script:
      - git clone -b test https://$REAL_REPO_OWNER:$my_og_token@github.com/projects-nexus/ci-script /tmp/cs
      - mv /tmp/cs/* /tmp/ci
      - bash down*
    symc_script:
      - bash sy*
    compile_script:
      - bash bu*
    upl_script:
      - bash upl*
