#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# wait for function script to clone
while true; do
    if [ -f "/tmp/ci/function" ]; then
        . /tmp/ci/function
        break
    else
        sleep 1
    fi
done

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

git config --global user.name "ImSpiDy"
echo "switching account"
gh config set -h github.com
login_main # main id
git config --global credential.helper '!gh auth git-credential'

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android -b lineage-19.1 --git-lfs -g default,-mips,-darwin,-notdefault
git clone https://github.com/wHo-EM-i/manifest.git --depth 1 -b 12.1 .repo/local_manifests

# Sync source without unnecessary messages, try with -j16 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

git clone https://github.com/ImSpiDy/device_xiaomi_lavender device/xiaomi/lavender -b 12.1
git clone --depth=1 https://github.com/ImSpiDy/device_xiaomi_sdm660-common device/xiaomi/sdm660-common -b 12.1
#git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_lavender vendor/xiaomi/lavender -b 11
#git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_xiaomi_sdm660-common vendor/xiaomi/sdm660-common -b 11
#git clone --depth=1 --single-branch https://github.com/ImSpiDy/sonix_kernel_sdm660 kernel/xiaomi/sdm660 -b sonix
git -C kernel/xiaomi/sdm660 apply old-rdp.p
#git -C kernel/xiaomi/sdm660 apply /tmp/ci/old-rdp.p

# extra stuff
#git clone --depth=1 --single-branch https://gitlab.com/Project-Nexus/nexus-clang.git /tmp/rom/prebuilts/clang/host/linux-x86/custom-clang -b nexus-14

# soc hals
rm -rf /tmp/rom/hardware/qcom-caf/sdm660/display
rm -rf /tmp/rom/hardware/qcom-caf/sdm660/audio
rm -rf /tmp/rom/hardware/qcom-caf/sdm660/media
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_audio hardware/qcom-caf/sdm660/audio -b 12-caf-sdm660
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_media hardware/qcom-caf/sdm660/media -b 12-caf-sdm660
git clone --depth=1 https://github.com/wHo-EM-i/hardware_qcom_display hardware/qcom-caf/sdm660/display -b 12-caf-sm8150

git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_camera hardware/qcom-caf/sdm660/camera -b sdm660-10.2.1.r1

git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi -b lineage-19.1
rm -rf hardware/xiaomi/megvii

# build/soong
#curl https://github.com/wHo-EM-i/build_soong/commit/42df79cee0b1eec108a71affcf3ae841613b9a0c.patch | git -C build/soong am
#curl https://github.com/wHo-EM-i/build_soong/commit/809cf30f6ee3183d630c40b5eef375fe1fd965a7.patch | git -C build/soong am
#curl https://github.com/wHo-EM-i/build_soong/commit/1f4a7bed507a34ca6e46a5ab5b4017899133cab0.patch | git -C build/soong am
#curl https://github.com/wHo-EM-i/build_soong/commit/0a769f9d183a692b9fd56dabd77aec7b2a80d980.patch | git -C build/soong am

#git -C build/soong fetch https://github.com/wHo-EM-i/build_soong -t 12.1
#git -C build/soong cherry-pick 68f350e53d7b82d412824b694acda4859bb97547^..b7cebda77a842ab60bccac07257ea2347846fd16

# fwb (for 3finger ss)
#curl https://github.com/wHo-EM-i/android_frameworks_base/commit/f33a3ab154fa728df3c77d05caf774dab0b50d63.patch | git -C frameworks/base am
#curl https://github.com/wHo-EM-i/android_frameworks_base/commit/a15d8fe10efb72f541c52d00d26d9bce52f1ba79.patch | git -C frameworks/base am
#curl https://github.com/wHo-EM-i/android_frameworks_base/commit/4a12db3bb0cb87f4efa910c9c575bd02cba5a81e.patch | git -C frameworks/base am

# keyboard theme
curl https://github.com/droid-legacy/android_packages_inputmethods_LatinIME/commit/7c2611719cf422ca7d80f5338b9e935c70b045ec.patch | git -C packages/inputmethods/LatinIME am

# AOR
#rm -rf external/arm-optimized-routines
#git clone --depth=1 https://github.com/projectarcana-aosp/android_external_arm-optimized-routines external/arm-optimized-routines

# Patch
#curl https://github.com/JunkYard-XD/android_vendor/commit/9a26c681fb11d932e44631565622e7b307e61aae.patch | git -C vendor/lineage am

#curl https://github.com/droid-legacy/android_build_make/commit/9f8049846eb61be7daadeb633f8207b27f00d330.patch | git -C build/make am

# qti powerhal
rm -rf /tmp/rom/vendor/qcom/opensource/power
git clone --depth=1 https://github.com/JunkYard-XD/android_vendor_qcom_opensource_power vendor/qcom/opensource/power -b 12.1

# keys
#git clone --depth=1 https://github.com/Los-Ext/vendor_lineage-priv_keys vendor/lineage-priv/keys
git clone https://github.com/Nub-XD/vendor_lavender-priv_keys vendor/lineage-priv/keys
echo "-include vendor/lineage-priv/keys/keys.mk" >> vendor/*/config/common.mk

git config --global user.name "$CIRRUS_REPO_OWNER"
echo "switching account" && gh auth logout
login_main # main id
gh config set -h github.com

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
