#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# wait for function script to clone
while true; do
    if [ -f "/tmp/ci/function" ]; then
        . /tmp/ci/function
        break
    else
        sleep 1
    fi
done

SECONDS=0

if [[ $git_cookies != 0 ]]; then
sudo touch /etc/mtab
sudo chmod 777 /etc/mtab
echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh
fi

git config --global user.name "ImSpiDy"
echo "switching account" 
gh config set -h github.com
login_main # main id
git config --global credential.helper '!gh auth git-credential'

#exit 0

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/DerpFest-AOSP/manifest -b 13 --git-lfs -g default,-mips,-darwin,-notdefault

# local_mnf
mkdir -p .repo/local_manifests && cp /tmp/ci/local_manifest.xml .repo/local_manifests

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# cleanupPostRender
grep -rl 'getRenderEngine().cleanupPostRender()' frameworks/native | xargs sed -i '/^[[:space:]]*\/\//! s/\(getRenderEngine().cleanupPostRender()\)/\/\/\1/'

# tree
if [ $K19 == 1 ]; then
git clone --single-branch --depth=1 https://github.com/ImSpiDy/sonix_kernel_sdm660 kernel/xiaomi/sdm660 -b scar
git -C kernel/xiaomi/sdm660 apply snx/old-rdp.p
#git clone --single-branch --depth=1 https://github.com/reaPeR1010/kernel_4.14 kernel/xiaomi/sdm660 -b newtest
else
git clone --depth=1 https://github.com/ImSpiDy/kernel_xiaomi_lavender-4.4 kernel/xiaomi/sdm660 -b snx-rdp
fi

git clone --depth=1 https://github.com/ImSpiDy/device_xiaomi_lavender device/xiaomi/lavender -b 13
#git -C device/xiaomi/lavender revert --no-edit c4be758e22889a9f79152cb65869cce9617a4036
#git -C device/xiaomi/lavender revert --no-edit e99ab4426a679cfd117c6eeb7ec36769b18ae71e

git clone --depth=1 https://github.com/ImSpiDy/device_xiaomi_sdm660-common device/xiaomi/sdm660-common -b 13

#git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_lavender vendor/xiaomi/lavender -b 13
#git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_xiaomi_sdm660-common vendor/xiaomi/sdm660-common -b 13
#git clone --depth=1 --single-branch https://github.com/wHo-EM-i/vendor_xiaomi_sdm660-common-4.4 vendor/xiaomi/sdm660-common-4.4 -b 13

rm -rf hardware/xiaomi
git clone --depth=1 https://github.com/arrowos-devices/android_hardware_xiaomi hardware/xiaomi -b arrow-13.1

#rm -rf device/xiaomi/lavender/libhidl
rm -rf hardware/xiaomi/megvii/*.bp

# patch
# bionic
#rm -rf /tmp/rom/bionic && git clone --depth=1 https://github.com/wHo-EM-i/bionic -b vos13
#curl https://github.com/wHo-EM-i/bionic/commit/585562aa03169194a2b0c32e72c752ff07a2c71d.patch | git -C bionic am

# soong patch
# r8 oom kill fix
#curl https://github.com/wHo-EM-i/build_soong/commit/22be3e99bd352172e1c2986d2646deefc3499c37.patch | git -C build/soong am
# disable zip compression 
curl https://github.com/wHo-EM-i/build_soong/commit/623d99004975217d4762e221ea84c34d2c5f98e6.patch | git -C build/soong am
# metalava soong kill fix
#curl https://github.com/VoltageOS/build_soong/commit/09d9cde9c48cd7f35c89aada8a5c56c1ee407ea7.patch | git -C build/soong am

# build_make
# brotli
#curl https://github.com/VoltageOS/build/commit/765c1bfe16e78fe8aec256e507d4dc1445187f5e.patch | git -C build/make am
# soong zip (multi threaded)
#curl https://github.com/wHo-EM-i/build/commit/530d84f56cd35cbf645aaf8574fc4df39799ea60.patch | git -C build/make am
#curl https://github.com/wHo-EM-i/build/commit/24116259c07fc438097d6fb168d380496d66f6a5.patch | git -C build/make am
#curl https://github.com/wHo-EM-i/build/commit/920a20cca2cccdb1161ab7135a70835db0c5508d.patch | git -C build/make am

# frameworks_native
#curl https://github.com/ArrowOS-Legacy/android_frameworks_native/commit/dabdcc7ed7cb126f61f8f48602be62d7944b6eee.patch | git -C frameworks/native am
#curl https://github.com/ArrowOS-Legacy/android_frameworks_native/commit/ee95d097a8686e37b14e80237b7299a3cca67a20.patch | git -C frameworks/native am

# fwb
#curl https://github.com/wHo-EM-i/android_frameworks_base/commit/d42ee32d3b4b82bf7e1275b7bdb1000cb7252061.patch | git -C frameworks/base am

# vendor_voltage
#curl https://github.com/wHo-EM-i/android_vendor_arrow/commit/09d98ff84e42287ab56fcd621aa1cf3d9933c2fe.patch | git -C vendor/voltage am
#curl https://github.com/wHo-EM-i/android_vendor_arrow/commit/80f9ec6fe8f1315597e5045bea5a9e8d919f3095.patch | git -C vendor/voltage am
#curl https://github.com/wHo-EM-i/android_vendor_arrow/commit/f6c03239496818df327613f203f1cec9fa04c9db.patch | git -C vendor/voltage am

# clang 17
#git clone --depth=1 https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r498229 prebuilts/clang/host/linux-x86/aosp-clang

# Hals
#if [ $K19 == 1 ]; then
#sed -i 's|QCOM_HARDWARE_VARIANT := msm8998|QCOM_HARDWARE_VARIANT := sdm660|' vendor/*/config/B*Qcom.mk
#else
#sed -i 's|QCOM_HARDWARE_VARIANT := sdm660|QCOM_HARDWARE_VARIANT := msm8998|' vendor/*/config/B*Qcom.mk
#fi
rm -rf hardware/qcom-caf/sdm660/audio hardware/qcom-caf/sdm660/media
rm -rf hardware/qcom-caf/sdm660/display
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_audio hardware/qcom-caf/sdm660/audio -b 13-caf-sdm660
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_media hardware/qcom-caf/sdm660/media -b 8.2.1
#mine
git clone --depth=1 https://github.com/wHo-EM-i/hardware_qcom_display hardware/qcom-caf/sdm660/display -b 13-caf-sm8150
#pix106
#git clone --depth=1 https://github.com/pix106/android_hardware_qcom-caf_display hardware/qcom-caf/sdm660/display -b lineage-22.1-caf-sdm660

git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_camera hardware/qcom-caf/sdm660/camera -b sdm660-4.19-11.2.1.r1

# keys
#git clone --depth=1 https://github.com/Los-Ext/vendor_lineage-priv_keys vendor/lineage-priv/keys
git clone https://github.com/Nub-XD/vendor_lavender-priv_keys vendor/lineage-priv/keys
echo "-include vendor/lineage-priv/keys/keys.mk" >> vendor/*/config/common.mk

git config --global user.name "$CIRRUS_REPO_OWNER"
echo "switching account" && gh auth logout
login_main # main id
gh config set -h github.com

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
