#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# wait for function script to clone
while true; do
    if [ -f "/tmp/ci/function" ]; then
        . /tmp/ci/function
        break
    else
        sleep 1
    fi
done

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

git config --global user.name "ImSpiDy"
echo "switching account" 
gh config set -h github.com
login_main # main id
git config --global credential.helper '!gh auth git-credential'

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/crdroid11/android.git -b 11.0 --git-lfs -g default,-mips,-darwin,-notdefault

# local_mnf
mkdir -p .repo/local_manifests && cp /tmp/ci/local_manifest.xml .repo/local_manifests

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

#crdeoid11 fuckers
curl https://github.com/LineageOS/android_packages_services_Mms/commit/e36db27f4f64b0c77db5af7e05305bdfdc0e0654.patch | git -C packages/services/Mms am
curl https://github.com/LineageOS/android_packages_services_Mms/commit/20eadc021d566984b62e9e190e2b84ba6371336a.patch | git -C packages/services/Mms am

# tree
if [ $K19 == 1 ]; then
git clone --depth=1 --single-branch https://github.com/ImSpiDy/sonix_kernel_sdm660 kernel/xiaomi/sdm660 -b scar
cd kernel/xiaomi/sdm660
#echo "Adding CONFIG_QCA_CLD_WLAN_LEGACY=y"
#echo "CONFIG_QCA_CLD_WLAN_LEGACY=y" >> arch/arm64/configs/lavender_defconfig
echo "Dropping RDP"
echo "# CONFIG_INITRAMFS_IGNORE_SKIP_FLAG is not set" >> arch/arm64/configs/lavender_defconfig
git apply snx/drop_rdp.p
#bash ksu.sh
#echo "CONFIG_KSU=y" >> arch/arm64/configs/lavender_defconfig
#echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/lavender_defconfig
cd /tmp/rom
else
git clone --depth=1 --single-branch https://github.com/ImSpiDy/kernel_xiaomi_lavender-4.4 kernel/xiaomi/sdm660 -b snx-qti
git -C kernel/xiaomi/sdm660 apply QTI_HAPTICS.p
fi
git clone https://github.com/ImSpiDy/device_xiaomi_lavender device/xiaomi/lavender -b 11
git clone --depth=1 https://github.com/ImSpiDy/device_xiaomi_sdm660-common device/xiaomi/sdm660-common -b 11

#git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_lavender vendor/xiaomi/lavender -b 11
#git clone --depth=1 --single-branch https://github.com/ImSpiDy/vendor_xiaomi_sdm660-common vendor/xiaomi/sdm660-common -b 11

git clone https://github.com/ImSpiDy/SonixExtra vendor/sonix -b inline
git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi -b lineage-18.1
rm -rf hardware/xiaomi/megvii

#rm -rf device/qcom/sepolicy-legacy-um
#git clone --depth=1 https://github.com/ArrowOS/android_device_qcom_sepolicy-legacy-um device/qcom/sepolicy-legacy-um -b arrow-13.1

#rm -rf device/xiaomi/lavender/libhidl

# patch
#rm -rf /tmp/rom/bionic
#git clone --depth=1 https://github.com/wHo-EM-i/bionic -b vos13

# Hals
rm -rf hardware/qcom-caf/sdm660/audio hardware/qcom-caf/sdm660/media hardware/qcom-caf/sdm660/display
sed -i 's|QCOM_HARDWARE_VARIANT := msm8998|QCOM_HARDWARE_VARIANT := sdm660|' vendor/*/config/B*Qcom.mk
if [ $K19 == 1 ]; then
#sed -i 's|QCOM_HARDWARE_VARIANT := msm8998|QCOM_HARDWARE_VARIANT := sdm660|' vendor/*/config/B*Qcom.mk
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_audio hardware/qcom-caf/sdm660/audio -b 11-caf-sdm660
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_media hardware/qcom-caf/sdm660/media -b 11-8.2.1
git clone --depth=1 https://github.com/wHo-EM-i/hardware_qcom_display hardware/qcom-caf/sdm660/display -b 11-caf-sm8150
else
#sed -i 's|QCOM_HARDWARE_VARIANT := sdm660|QCOM_HARDWARE_VARIANT := msm8998|' vendor/*/config/B*Qcom.mk
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_audio hardware/qcom-caf/sdm660/audio -b sdm660-4.4
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_media hardware/qcom-caf/sdm660/media -b sdm660-4.4
git clone --depth=1 https://github.com/wHo-EM-i/hardware_qcom_display hardware/qcom-caf/sdm660/display -b 11-9.2.r1
fi
git clone --depth=1 https://github.com/wHo-EM-i/android_hardware_qcom_camera hardware/qcom-caf/sdm660/camera -b sdm660-9.2.r1

# keys
#git clone --depth=1 https://github.com/Los-Ext/vendor_lineage-priv_keys vendor/lineage-priv/keys
git clone https://github.com/Nub-XD/vendor_lavender-priv_keys vendor/lineage-priv/keys
echo "-include vendor/lineage-priv/keys/keys.mk" >> vendor/*/config/common.mk

#patch
rm -rf device/qcom/sepolicy-legacy-um
git clone https://github.com/raiyanbinmohsin/device_qcom_sepolicy-legacy-um device/qcom/sepolicy-legacy-um
git -C device/qcom/sepolicy-legacy-um revert -n b63cd988f7e7df3d54a97285f354476760edf7ae

# build/soong
curl https://github.com/wHo-EM-i/build_soong/commit/42df79cee0b1eec108a71affcf3ae841613b9a0c.patch | git -C build/soong am
#curl https://github.com/wHo-EM-i/build_soong/commit/809cf30f6ee3183d630c40b5eef375fe1fd965a7.patch | git -C build/soong am
curl https://github.com/wHo-EM-i/build_soong/commit/1f4a7bed507a34ca6e46a5ab5b4017899133cab0.patch | git -C build/soong am
curl https://github.com/wHo-EM-i/build_soong/commit/0a769f9d183a692b9fd56dabd77aec7b2a80d980.patch | git -C build/soong am
# bionic
#curl https://github.com/crdroidandroid/android_bionic/commit/1bc81a661fac286b709f6c424e260ff863dfad5c.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/35990d0980cacda546da37870d26f19058f2ce17.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/1b0f29cc939cd54b6d05d831e7bdb027df26d48f.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/51eede079a2ffea774387b5bc85acf3045a2d540.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/39d3922e99268aae398bff4be4f665d04a57e996.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/503eee1d788c15e489a565d1e309b89c926f40af.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/95558dd34bf0b7c8fa995f72974a0d54ec5bd044.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/39d0bc4270a07cb5212f4deacf53d6585a0607f6.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/aac77981473662b7a71f2a1fa2463bff0f423efa.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/48cec51f241f87811dabc65e27fc5bb094676231.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/54de6110d3c55be0573c358661ce0439f5bd25e0.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/4114593175e1bc96925be734a80551c6c1502379.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/fbacd1563238aa2518971171e4d95cca61326cb8.patch | git -C bionic am
#curl https://github.com/crdroidandroid/android_bionic/commit/7d66f1fb333114f7e35a2bd33e428d66b70e72ca.patch | git -C bionic am

# hax
# fwb
#curl https://github.com/xdCLO-Enhanced/xd_frameworks_base/commit/efb19839c2215e4d087d9286b76c73c8ae15c701.patch | git -C frameworks/base am
#rm -rf frameworks/base; git clone --single-branch --depth=1 https://github.com/JunkYard-XD/android_frameworks_base frameworks/base -b 11.0
#git -C frameworks/base fetch https://github.com/JunkYard-XD/android_frameworks_base -t 11.0
#git -C frameworks/base cherry-pick d8be6329bcdfc9f384a350d04008f7e6853512eb^..3b6a25be3ad541488105bea9d7acdefae23f88e1
# PPU (prop based impl)
#git -C frameworks/base cherry-pick 87b4c62e3cbab2da36656dfddaf750aa1e008691
# BL Lock spoof
#git -C frameworks/base cherry-pick 07651054fe4bd97922d8ff80e97f2ff85c19115b

#git -C vendor/lineage fetch https://github.com/JunkYard-XD/android_vendor -t 11.0
# disable gms spoof overlay
#git -C vendor/lineage cherry-pick 39726c50c836b535553a5a983a7c9eeadef2bcce

# Settings (maintainer patch)
curl https://github.com/JunkYard-XD/android_packages_apps_Settings/commit/01592a8ca348aa94755c910779d8b3b23b45c395.patch | git -C packages/apps/Settings am

# Clang
#git clone --depth=1 --single-branch https://gitlab.com/Project-Nexus/nexus-clang.git prebuilts/clang/host/linux-x86/custom-clang -b nexus-14

#mkdir -p prebuilts/clang/host/linux-x86/custom-clang
#curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-prebuilts/clang-r574158.tar.gz -o /tmp/rom/clang-r574158.tar.gz
#aria2c https://github.com/JunkYard-XD/roms-cache/releases/download/Test/clang-r574158.tar.gz -x16 -s50
#tar -xzf clang-*.tar.gz -C /tmp/rom/prebuilts/clang/host/linux-x86/custom-clang && rm -rf clang-*.tar.gz

# qti powerhal
#rm -rf /tmp/rom/vendor/qcom/opensource/power
#git clone --depth=1 https://github.com/JunkYard-XD/android_vendor_qcom_opensource_power vendor/qcom/opensource/power -b 11.0

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute and $(($SECONDS % 60)) second.
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt

